"""Immutable local evidence ledger for trading decisions and outcomes.

The ledger is deliberately separate from execution.  It has no credential,
network, signer, or venue-write dependency.  Every mutation is an append to a
SQLite hash chain; SQL triggers reject updates and deletes.  Monetary values
are exact :class:`~decimal.Decimal` values and binary floats are rejected.

Two timestamps have intentionally different meanings:

* ``recorded_at`` is generated by the ledger clock and may never move
  backwards.  Callers cannot provide it, which prevents audit backdating.
* ``occurred_at`` and evidence timestamps describe external facts.  They may
  predate ingestion (for example, a fill discovered during reconciliation),
  but are permanently committed by the event hash.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable, Mapping
from contextlib import closing
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from decimal import Decimal, InvalidOperation, localcontext
from enum import Enum
import json
from pathlib import Path
import re
import sqlite3
from typing import Any

from .canonical import canonical_data, canonical_json, domain_hash, validate_decimal_bounds
from .executor_state_binding import (
    MAX_SHARED_STATE_FILE_BYTES,
    STATE_BINDING_TABLE,
    STATE_BINDING_TABLE_SQL,
)
from .errors import StorageError
from .sqlite_snapshot import (
    enforce_sqlite_write_limit,
    sqlite_verification_snapshot,
    validate_sqlite_file_sizes,
)


LEDGER_SCHEMA_VERSION = 1
EVENT_SCHEMA_VERSION = 1
LEDGER_GENESIS_HASH = "0" * 64
EVENT_CONTENT_DOMAIN = "trading-harness/learning-ledger/event-content/v1"
EVENT_CHAIN_DOMAIN = "trading-harness/learning-ledger/event-chain/v1"
EVENT_ID_DOMAIN = "trading-harness/learning-ledger/event-id/v1"
MARKET_PATH_DOMAIN = "trading-harness/learning-ledger/market-path/v1"
FILL_NATURAL_KEY_DOMAIN = "trading-harness/learning-ledger/venue-fill-key/v1"
COUNTERFACTUAL_KEY_DOMAIN = "trading-harness/learning-ledger/counterfactual-key/v1"
CLOSE_CORRECTION_KEY_DOMAIN = "trading-harness/learning-ledger/close-correction-key/v1"
COUNTERFACTUAL_DERIVATION_VERSION = "entry-aware-conservative-bracket-path/v2"
MAX_DECISION_INGEST_LAG = timedelta(minutes=5)
MAX_LEARNING_EVENT_BYTES = 1024 * 1024
_LEARNING_WRITE_HEADROOM_BYTES = 2 * 1024 * 1024

_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")

_EXPECTED_LEDGER_COLUMNS = {
    "learning_ledger_meta": ("key", "value"),
    "learning_ledger_events": (
        "sequence",
        "event_id",
        "event_type",
        "cycle_id",
        "semantic_key",
        "idempotency_key",
        "occurred_at",
        "recorded_at",
        "payload_json",
        "content_hash",
        "previous_hash",
        "event_hash",
        "schema_version",
    ),
}

_EXPECTED_LEDGER_SCHEMA_SQL = {
    "learning_ledger_meta": """
        CREATE TABLE learning_ledger_meta (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        ) WITHOUT ROWID
    """,
    "learning_ledger_events": """
        CREATE TABLE learning_ledger_events (
            sequence INTEGER PRIMARY KEY,
            event_id TEXT NOT NULL UNIQUE,
            event_type TEXT NOT NULL,
            cycle_id TEXT NOT NULL,
            semantic_key TEXT NOT NULL,
            idempotency_key TEXT NOT NULL UNIQUE,
            occurred_at TEXT NOT NULL,
            recorded_at TEXT NOT NULL,
            payload_json TEXT NOT NULL,
            content_hash TEXT NOT NULL,
            previous_hash TEXT NOT NULL,
            event_hash TEXT NOT NULL UNIQUE,
            schema_version INTEGER NOT NULL,
            UNIQUE(event_type, semantic_key)
        )
    """,
    "learning_ledger_cycle_sequence": """
        CREATE INDEX learning_ledger_cycle_sequence
        ON learning_ledger_events(cycle_id, sequence)
    """,
    "learning_ledger_no_update": """
        CREATE TRIGGER learning_ledger_no_update
        BEFORE UPDATE ON learning_ledger_events
        BEGIN
            SELECT RAISE(ABORT, 'learning ledger events are immutable');
        END
    """,
    "learning_ledger_no_delete": """
        CREATE TRIGGER learning_ledger_no_delete
        BEFORE DELETE ON learning_ledger_events
        BEGIN
            SELECT RAISE(ABORT, 'learning ledger events are immutable');
        END
    """,
}


def _normalized_schema_sql(value: object) -> str:
    if not isinstance(value, str):
        return ""
    return " ".join(value.rstrip("; ").split()).lower()


class LearningLedgerError(RuntimeError):
    """Base exception for learning-ledger failures."""


class LedgerIntegrityError(LearningLedgerError):
    """Raised when persisted bytes do not match the append-only hash chain."""


class IdempotencyConflict(LearningLedgerError):
    """Raised when an idempotency key is reused for different content."""


class DuplicateConflict(LearningLedgerError):
    """Raised when a logical record is repeated under another key."""


class LedgerBackdatingError(LearningLedgerError):
    """Raised when the local append clock moves behind the durable head."""


class LifecycleError(LearningLedgerError):
    """Raised when evidence would create an impossible learning lifecycle."""


class _StringEnum(str, Enum):
    def __str__(self) -> str:
        return self.value


class DecisionClass(_StringEnum):
    BUY = "buy"
    SELL = "sell"
    NOTHING = "nothing"
    UNAVAILABLE = "unavailable"


class ApprovalState(_StringEnum):
    REQUESTED = "requested"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXPIRED = "expired"
    REVOKED = "revoked"


class ExecutionState(_StringEnum):
    STAGED = "staged"
    AUTHORIZED = "authorized"
    DISPATCHED = "dispatched"
    ACKNOWLEDGED = "acknowledged"
    UNKNOWN = "unknown"
    RECONCILED = "reconciled"
    REJECTED = "rejected"
    VOIDED = "voided"


class FillRole(_StringEnum):
    ENTRY = "entry"
    EXIT = "exit"
    PROTECTION = "protection"


class ExitReason(_StringEnum):
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"
    MANUAL = "manual"
    SIGNAL = "signal"
    TIME_LIMIT = "time_limit"
    LIQUIDATION = "liquidation"
    VENUE = "venue"
    OTHER = "other"


class CounterfactualEntryRule(_StringEnum):
    """Deterministic activation rule for a hypothetical bracket."""

    TOUCH = "touch"
    WINDOW_OPEN = "window_open"


def _text(value: Any, field_name: str) -> str:
    if not isinstance(value, str) or not value or value != value.strip():
        raise ValueError(f"{field_name} must be a non-empty, trimmed string")
    if "\x00" in value:
        raise ValueError(f"{field_name} must not contain NUL")
    return value


def _optional_text(value: Any, field_name: str) -> str | None:
    if value is None:
        return None
    return _text(value, field_name)


def _sha256(value: Any, field_name: str) -> str:
    result = _text(value, field_name)
    if not _SHA256_RE.fullmatch(result):
        raise ValueError(f"{field_name} must be a lowercase SHA-256 digest")
    return result


def _optional_sha256(value: Any, field_name: str) -> str | None:
    if value is None:
        return None
    return _sha256(value, field_name)


def _utc(value: Any, field_name: str) -> datetime:
    if not isinstance(value, datetime):
        raise TypeError(f"{field_name} must be datetime")
    if value.tzinfo is None or value.utcoffset() is None:
        raise ValueError(f"{field_name} must be timezone-aware")
    return value.astimezone(timezone.utc)


def _iso(value: datetime) -> str:
    return _utc(value, "timestamp").isoformat(timespec="microseconds").replace(
        "+00:00", "Z"
    )


def _parse_iso(value: str, field_name: str) -> datetime:
    if not isinstance(value, str):
        raise TypeError(f"{field_name} must be an ISO-8601 string")
    encoded = value[:-1] + "+00:00" if value.endswith("Z") else value
    try:
        parsed = datetime.fromisoformat(encoded)
    except ValueError as error:
        raise ValueError(f"{field_name} must be an ISO-8601 timestamp") from error
    return _utc(parsed, field_name)


def _exact_decimal(
    value: Any,
    field_name: str,
    *,
    positive: bool = False,
    nonnegative: bool = False,
    optional: bool = False,
) -> Decimal | None:
    if value is None and optional:
        return None
    if isinstance(value, (float, bool)):
        raise TypeError(f"{field_name} must be Decimal, int, or exact string; floats are forbidden")
    if isinstance(value, Decimal):
        result = value
    elif isinstance(value, int):
        result = Decimal(value)
    elif isinstance(value, str):
        if not value or value != value.strip():
            raise ValueError(f"{field_name} must be a trimmed exact decimal")
        try:
            result = Decimal(value)
        except InvalidOperation as error:
            raise ValueError(f"{field_name} is not an exact decimal") from error
    else:
        raise TypeError(f"{field_name} must be Decimal, int, or exact string")
    validate_decimal_bounds(result, field=field_name)
    if positive and result <= 0:
        raise ValueError(f"{field_name} must be greater than zero")
    if nonnegative and result < 0:
        raise ValueError(f"{field_name} must be non-negative")
    return result


def _ratio(numerator: Decimal, denominator: Decimal) -> Decimal:
    if denominator == 0:
        raise ValueError("ratio denominator must not be zero")
    with localcontext() as context:
        context.prec = 50
        result = numerator / denominator
    validate_decimal_bounds(result, field="derived ratio")
    return result


def _add_exact(*values: Decimal) -> Decimal:
    with localcontext() as context:
        context.prec = 256
        return sum(values, Decimal(0))


def _subtract_exact(left: Decimal, right: Decimal) -> Decimal:
    with localcontext() as context:
        context.prec = 256
        return left - right


def _multiply_exact(left: Decimal, right: Decimal) -> Decimal:
    with localcontext() as context:
        context.prec = 256
        return left * right


def _sum_exact(values: Iterable[Decimal]) -> Decimal:
    with localcontext() as context:
        context.prec = 256
        return sum(values, Decimal(0))


def _enum(value: Any, enum_type: type[_StringEnum], field_name: str) -> _StringEnum:
    if isinstance(value, enum_type):
        return value
    if isinstance(value, str):
        try:
            return enum_type(value)
        except ValueError as error:
            raise ValueError(f"invalid {field_name}: {value!r}") from error
    raise TypeError(f"{field_name} must be {enum_type.__name__} or str")


def _string_tuple(value: Iterable[str], field_name: str, *, empty_ok: bool = True) -> tuple[str, ...]:
    if isinstance(value, str):
        raise TypeError(f"{field_name} must be an iterable of strings, not str")
    result = tuple(_text(item, field_name) for item in value)
    if not empty_ok and not result:
        raise ValueError(f"{field_name} must not be empty")
    if len(set(result)) != len(result):
        raise ValueError(f"{field_name} must not contain duplicates")
    return result


@dataclass(frozen=True, slots=True)
class SourceEvidence:
    """Hash-only reference to TA, sentiment, market, or availability evidence."""

    source_id: str
    source_kind: str
    content_hash: str
    observed_at: datetime
    captured_at: datetime
    source_version: str
    locator: str | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "source_id", _text(self.source_id, "source_id"))
        object.__setattr__(self, "source_kind", _text(self.source_kind, "source_kind"))
        object.__setattr__(self, "content_hash", _sha256(self.content_hash, "content_hash"))
        object.__setattr__(self, "observed_at", _utc(self.observed_at, "observed_at"))
        object.__setattr__(self, "captured_at", _utc(self.captured_at, "captured_at"))
        object.__setattr__(self, "source_version", _text(self.source_version, "source_version"))
        object.__setattr__(self, "locator", _optional_text(self.locator, "locator"))
        if self.captured_at < self.observed_at:
            raise ValueError("captured_at must not precede observed_at")


@dataclass(frozen=True, slots=True)
class ComponentVersions:
    """Exact versions responsible for a decision."""

    strategy_version: str
    configuration_version: str
    code_hash: str
    decision_rule_version: str
    ta_version: str
    sentiment_version: str
    risk_policy_version: str

    def __post_init__(self) -> None:
        for name in (
            "strategy_version",
            "configuration_version",
            "decision_rule_version",
            "ta_version",
            "sentiment_version",
            "risk_policy_version",
        ):
            object.__setattr__(self, name, _text(getattr(self, name), name))
        object.__setattr__(self, "code_hash", _sha256(self.code_hash, "code_hash"))


@dataclass(frozen=True, slots=True)
class ProposedBracket:
    """Proposed position economics; a stop is structurally mandatory."""

    side: DecisionClass
    entry_price: Decimal
    stop_price: Decimal
    target_price: Decimal
    quantity: Decimal
    risk_amount: Decimal
    settlement_asset: str
    planned_reward_risk: Decimal = field(init=False)

    def __post_init__(self) -> None:
        side = _enum(self.side, DecisionClass, "side")
        if side not in (DecisionClass.BUY, DecisionClass.SELL):
            raise ValueError("bracket side must be buy or sell")
        object.__setattr__(self, "side", side)
        for name in ("entry_price", "stop_price", "target_price", "quantity", "risk_amount"):
            object.__setattr__(
                self,
                name,
                _exact_decimal(getattr(self, name), name, positive=True),
            )
        object.__setattr__(
            self, "settlement_asset", _text(self.settlement_asset, "settlement_asset").upper()
        )
        if side is DecisionClass.BUY:
            if not self.stop_price < self.entry_price < self.target_price:
                raise ValueError("buy bracket requires stop < entry < target")
            reward = _subtract_exact(self.target_price, self.entry_price)
            risk = _subtract_exact(self.entry_price, self.stop_price)
        else:
            if not self.target_price < self.entry_price < self.stop_price:
                raise ValueError("sell bracket requires target < entry < stop")
            reward = _subtract_exact(self.entry_price, self.target_price)
            risk = _subtract_exact(self.stop_price, self.entry_price)
        object.__setattr__(self, "planned_reward_risk", _ratio(reward, risk))


@dataclass(frozen=True, slots=True)
class DecisionCycle:
    """One scheduled decision, including abstentions and unavailable cycles."""

    cycle_id: str
    asset: str
    instrument: str
    venue: str
    environment: str
    timeframe: str
    decided_at: datetime
    classification: DecisionClass
    rationale_code: str
    thesis_hash: str
    versions: ComponentVersions
    evidence: tuple[SourceEvidence, ...]
    confidence: Decimal | None = None
    bracket: ProposedBracket | None = None
    tags: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        for name in ("cycle_id", "asset", "instrument", "venue", "environment", "timeframe", "rationale_code"):
            value = _text(getattr(self, name), name)
            if name == "asset":
                value = value.upper()
            object.__setattr__(self, name, value)
        object.__setattr__(self, "decided_at", _utc(self.decided_at, "decided_at"))
        classification = _enum(self.classification, DecisionClass, "classification")
        object.__setattr__(self, "classification", classification)
        object.__setattr__(self, "thesis_hash", _sha256(self.thesis_hash, "thesis_hash"))
        if not isinstance(self.versions, ComponentVersions):
            raise TypeError("versions must be ComponentVersions")
        evidence = tuple(self.evidence)
        if not evidence or not all(isinstance(item, SourceEvidence) for item in evidence):
            raise ValueError("evidence must contain at least one SourceEvidence")
        if len({item.source_id for item in evidence}) != len(evidence):
            raise ValueError("evidence source_id values must be unique")
        if any(item.captured_at > self.decided_at for item in evidence):
            raise ValueError("decision evidence cannot be captured after decided_at")
        object.__setattr__(
            self,
            "evidence",
            tuple(sorted(evidence, key=lambda item: (item.source_id, item.content_hash))),
        )
        confidence = _exact_decimal(
            self.confidence, "confidence", nonnegative=True, optional=True
        )
        if confidence is not None and confidence > 1:
            raise ValueError("confidence must be between zero and one")
        object.__setattr__(self, "confidence", confidence)
        object.__setattr__(self, "tags", tuple(sorted(_string_tuple(self.tags, "tags"))))
        if classification in (DecisionClass.BUY, DecisionClass.SELL):
            if not isinstance(self.bracket, ProposedBracket):
                raise ValueError("buy/sell decisions require a proposed bracket with stop")
            if self.bracket.side is not classification:
                raise ValueError("bracket side must match decision classification")
        elif self.bracket is not None:
            raise ValueError("nothing/unavailable decisions must not propose a position")


@dataclass(frozen=True, slots=True)
class ApprovalReference:
    cycle_id: str
    reference_id: str
    state: ApprovalState
    occurred_at: datetime
    ticket_hash: str
    authority_kind: str
    authority_evidence_hash: str | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "cycle_id", _text(self.cycle_id, "cycle_id"))
        object.__setattr__(self, "reference_id", _text(self.reference_id, "reference_id"))
        object.__setattr__(self, "state", _enum(self.state, ApprovalState, "state"))
        object.__setattr__(self, "occurred_at", _utc(self.occurred_at, "occurred_at"))
        object.__setattr__(self, "ticket_hash", _sha256(self.ticket_hash, "ticket_hash"))
        object.__setattr__(self, "authority_kind", _text(self.authority_kind, "authority_kind"))
        object.__setattr__(
            self,
            "authority_evidence_hash",
            _optional_sha256(self.authority_evidence_hash, "authority_evidence_hash"),
        )


@dataclass(frozen=True, slots=True)
class ExecutionReference:
    cycle_id: str
    command_id: str
    state: ExecutionState
    occurred_at: datetime
    execution_record_hash: str
    client_order_ids: tuple[str, ...]

    def __post_init__(self) -> None:
        object.__setattr__(self, "cycle_id", _text(self.cycle_id, "cycle_id"))
        object.__setattr__(self, "command_id", _text(self.command_id, "command_id"))
        object.__setattr__(self, "state", _enum(self.state, ExecutionState, "state"))
        object.__setattr__(self, "occurred_at", _utc(self.occurred_at, "occurred_at"))
        object.__setattr__(
            self,
            "execution_record_hash",
            _sha256(self.execution_record_hash, "execution_record_hash"),
        )


@dataclass(frozen=True, slots=True)
class RecoveryExecutionReference:
    cycle_id: str
    parent_command_id: str
    recovery_command_id: str
    kind: str
    occurred_at: datetime
    recovery_record_hash: str
    client_order_ids: tuple[str, ...]

    def __post_init__(self) -> None:
        object.__setattr__(self, "cycle_id", _text(self.cycle_id, "cycle_id"))
        object.__setattr__(
            self,
            "parent_command_id",
            _text(self.parent_command_id, "parent_command_id"),
        )
        object.__setattr__(
            self,
            "recovery_command_id",
            _text(self.recovery_command_id, "recovery_command_id"),
        )
        if self.kind != "reduce_only_close":
            raise ValueError("only recovery closes may bind fill order IDs")
        object.__setattr__(self, "occurred_at", _utc(self.occurred_at, "occurred_at"))
        object.__setattr__(
            self,
            "recovery_record_hash",
            _sha256(self.recovery_record_hash, "recovery_record_hash"),
        )
        object.__setattr__(
            self,
            "client_order_ids",
            _string_tuple(self.client_order_ids, "client_order_ids", empty_ok=False),
        )
        if len(self.client_order_ids) != 1:
            raise ValueError("recovery close must bind exactly one client order ID")
        object.__setattr__(
            self,
            "client_order_ids",
            _string_tuple(self.client_order_ids, "client_order_ids", empty_ok=False),
        )


@dataclass(frozen=True, slots=True)
class VenueFill:
    cycle_id: str
    command_id: str
    fill_id: str
    order_id: str
    client_order_id: str
    role: FillRole
    side: DecisionClass
    venue_occurred_at: datetime
    observed_at: datetime
    price: Decimal
    reference_price: Decimal
    quantity: Decimal
    fee: Decimal
    fee_asset: str
    venue_evidence_hash: str
    venue_closed_pnl: Decimal | None = None
    venue_pnl_asset: str | None = None
    slippage_bps: Decimal = field(init=False)
    latency_us: int = field(init=False)

    def __post_init__(self) -> None:
        for name in ("cycle_id", "command_id", "fill_id", "order_id", "client_order_id"):
            object.__setattr__(self, name, _text(getattr(self, name), name))
        object.__setattr__(self, "role", _enum(self.role, FillRole, "role"))
        side = _enum(self.side, DecisionClass, "side")
        if side not in (DecisionClass.BUY, DecisionClass.SELL):
            raise ValueError("fill side must be buy or sell")
        object.__setattr__(self, "side", side)
        object.__setattr__(
            self, "venue_occurred_at", _utc(self.venue_occurred_at, "venue_occurred_at")
        )
        object.__setattr__(self, "observed_at", _utc(self.observed_at, "observed_at"))
        if self.observed_at < self.venue_occurred_at:
            raise ValueError("observed_at must not precede venue_occurred_at")
        for name in ("price", "reference_price", "quantity"):
            object.__setattr__(self, name, _exact_decimal(getattr(self, name), name, positive=True))
        object.__setattr__(self, "fee", _exact_decimal(self.fee, "fee", nonnegative=True))
        object.__setattr__(self, "fee_asset", _text(self.fee_asset, "fee_asset").upper())
        object.__setattr__(
            self,
            "venue_evidence_hash",
            _sha256(self.venue_evidence_hash, "venue_evidence_hash"),
        )
        if (self.venue_closed_pnl is None) != (self.venue_pnl_asset is None):
            raise ValueError(
                "venue_closed_pnl and venue_pnl_asset must be present together"
            )
        if self.venue_closed_pnl is not None:
            object.__setattr__(
                self,
                "venue_closed_pnl",
                _exact_decimal(self.venue_closed_pnl, "venue_closed_pnl"),
            )
            asset = _text(self.venue_pnl_asset, "venue_pnl_asset").upper()
            if asset != self.fee_asset:
                raise ValueError(
                    "venue PnL asset must match the decision settlement asset"
                )
            object.__setattr__(self, "venue_pnl_asset", asset)
        signed_delta = _subtract_exact(self.price, self.reference_price)
        if side is DecisionClass.SELL:
            signed_delta = -signed_delta
        object.__setattr__(
            self,
            "slippage_bps",
            _ratio(_multiply_exact(signed_delta, Decimal(10_000)), self.reference_price),
        )
        latency = self.observed_at - self.venue_occurred_at
        latency_us = latency.days * 86_400_000_000 + latency.seconds * 1_000_000 + latency.microseconds
        object.__setattr__(self, "latency_us", latency_us)


@dataclass(frozen=True, slots=True)
class FundingPayment:
    cycle_id: str
    funding_id: str
    occurred_at: datetime
    amount: Decimal
    asset: str
    rate: Decimal
    position_quantity: Decimal
    venue_evidence_hash: str

    def __post_init__(self) -> None:
        object.__setattr__(self, "cycle_id", _text(self.cycle_id, "cycle_id"))
        object.__setattr__(self, "funding_id", _text(self.funding_id, "funding_id"))
        object.__setattr__(self, "occurred_at", _utc(self.occurred_at, "occurred_at"))
        object.__setattr__(self, "amount", _exact_decimal(self.amount, "amount"))
        object.__setattr__(self, "asset", _text(self.asset, "asset").upper())
        object.__setattr__(self, "rate", _exact_decimal(self.rate, "rate"))
        object.__setattr__(
            self,
            "position_quantity",
            _exact_decimal(self.position_quantity, "position_quantity", positive=True),
        )
        object.__setattr__(
            self,
            "venue_evidence_hash",
            _sha256(self.venue_evidence_hash, "venue_evidence_hash"),
        )


@dataclass(frozen=True, slots=True)
class MarketBar:
    opened_at: datetime
    closed_at: datetime
    open: Decimal
    high: Decimal
    low: Decimal
    close: Decimal

    def __post_init__(self) -> None:
        object.__setattr__(self, "opened_at", _utc(self.opened_at, "opened_at"))
        object.__setattr__(self, "closed_at", _utc(self.closed_at, "closed_at"))
        if self.closed_at <= self.opened_at:
            raise ValueError("bar closed_at must be after opened_at")
        for name in ("open", "high", "low", "close"):
            object.__setattr__(self, name, _exact_decimal(getattr(self, name), name, positive=True))
        if self.high < max(self.open, self.close) or self.low > min(self.open, self.close):
            raise ValueError("bar high/low do not contain open and close")
        if self.high < self.low:
            raise ValueError("bar high must not be below low")


@dataclass(frozen=True, slots=True)
class MarketPathEvidence:
    cycle_id: str
    path_id: str
    source_id: str
    source_snapshot_hash: str
    source_version: str
    window_started_at: datetime
    window_ended_at: datetime
    captured_at: datetime
    bars: tuple[MarketBar, ...]

    def __post_init__(self) -> None:
        for name in ("cycle_id", "path_id", "source_id", "source_version"):
            object.__setattr__(self, name, _text(getattr(self, name), name))
        object.__setattr__(
            self,
            "source_snapshot_hash",
            _sha256(self.source_snapshot_hash, "source_snapshot_hash"),
        )
        object.__setattr__(
            self, "window_started_at", _utc(self.window_started_at, "window_started_at")
        )
        object.__setattr__(
            self, "window_ended_at", _utc(self.window_ended_at, "window_ended_at")
        )
        object.__setattr__(self, "captured_at", _utc(self.captured_at, "captured_at"))
        if self.window_ended_at <= self.window_started_at:
            raise ValueError("market path window must have positive duration")
        if self.captured_at < self.window_ended_at:
            raise ValueError("captured_at must not precede the path window end")
        bars = tuple(self.bars)
        if not bars or not all(isinstance(bar, MarketBar) for bar in bars):
            raise ValueError("bars must contain at least one MarketBar")
        if bars[0].opened_at != self.window_started_at:
            raise ValueError("first bar must start exactly at the market-path window")
        if bars[-1].closed_at != self.window_ended_at:
            raise ValueError("final bar must end exactly at the market-path window")
        if any(left.closed_at != right.opened_at for left, right in zip(bars, bars[1:])):
            raise ValueError("market-path bars must be contiguous and non-overlapping")
        object.__setattr__(self, "bars", bars)


@dataclass(frozen=True, slots=True)
class CloseObservation:
    cycle_id: str
    close_id: str
    completed_at: datetime
    exit_reason: ExitReason
    exit_price: Decimal
    gross_pnl: Decimal
    pnl_asset: str
    close_evidence_hash: str

    def __post_init__(self) -> None:
        object.__setattr__(self, "cycle_id", _text(self.cycle_id, "cycle_id"))
        object.__setattr__(self, "close_id", _text(self.close_id, "close_id"))
        object.__setattr__(self, "completed_at", _utc(self.completed_at, "completed_at"))
        object.__setattr__(self, "exit_reason", _enum(self.exit_reason, ExitReason, "exit_reason"))
        object.__setattr__(self, "exit_price", _exact_decimal(self.exit_price, "exit_price", positive=True))
        object.__setattr__(self, "gross_pnl", _exact_decimal(self.gross_pnl, "gross_pnl"))
        object.__setattr__(self, "pnl_asset", _text(self.pnl_asset, "pnl_asset").upper())
        object.__setattr__(
            self,
            "close_evidence_hash",
            _sha256(self.close_evidence_hash, "close_evidence_hash"),
        )


@dataclass(frozen=True, slots=True)
class ClosePnlCorrection:
    """Append-only replacement for a gross-P&L observation after reconciliation."""

    cycle_id: str
    correction_id: str
    observed_at: datetime
    gross_pnl: Decimal
    pnl_asset: str
    reason_code: str
    reconciliation_evidence_hash: str

    def __post_init__(self) -> None:
        object.__setattr__(self, "cycle_id", _text(self.cycle_id, "cycle_id"))
        object.__setattr__(
            self, "correction_id", _text(self.correction_id, "correction_id")
        )
        object.__setattr__(self, "observed_at", _utc(self.observed_at, "observed_at"))
        object.__setattr__(self, "gross_pnl", _exact_decimal(self.gross_pnl, "gross_pnl"))
        object.__setattr__(self, "pnl_asset", _text(self.pnl_asset, "pnl_asset").upper())
        object.__setattr__(self, "reason_code", _text(self.reason_code, "reason_code"))
        object.__setattr__(
            self,
            "reconciliation_evidence_hash",
            _sha256(
                self.reconciliation_evidence_hash,
                "reconciliation_evidence_hash",
            ),
        )


@dataclass(frozen=True, slots=True)
class CounterfactualSpec:
    scenario_id: str
    side: DecisionClass
    entry_price: Decimal
    stop_price: Decimal
    target_price: Decimal
    entry_rule: "CounterfactualEntryRule"
    cost_r: Decimal
    max_bars: int
    scenario_version: str

    def __post_init__(self) -> None:
        object.__setattr__(self, "scenario_id", _text(self.scenario_id, "scenario_id"))
        side = _enum(self.side, DecisionClass, "side")
        if side not in (DecisionClass.BUY, DecisionClass.SELL):
            raise ValueError("counterfactual side must be buy or sell")
        object.__setattr__(self, "side", side)
        object.__setattr__(
            self,
            "entry_rule",
            _enum(self.entry_rule, CounterfactualEntryRule, "entry_rule"),
        )
        for name in ("entry_price", "stop_price", "target_price"):
            object.__setattr__(self, name, _exact_decimal(getattr(self, name), name, positive=True))
        object.__setattr__(self, "cost_r", _exact_decimal(self.cost_r, "cost_r", nonnegative=True))
        if isinstance(self.max_bars, bool) or not isinstance(self.max_bars, int) or self.max_bars <= 0:
            raise ValueError("max_bars must be a positive integer")
        object.__setattr__(self, "scenario_version", _text(self.scenario_version, "scenario_version"))
        if side is DecisionClass.BUY:
            valid = self.stop_price < self.entry_price < self.target_price
        else:
            valid = self.target_price < self.entry_price < self.stop_price
        if not valid:
            raise ValueError("counterfactual bracket is invalid for side")


@dataclass(frozen=True, slots=True)
class LedgerEvent:
    sequence: int
    event_id: str
    event_type: str
    cycle_id: str
    semantic_key: str
    idempotency_key: str
    occurred_at: datetime
    recorded_at: datetime
    payload: Mapping[str, Any]
    content_hash: str
    previous_hash: str
    event_hash: str
    schema_version: int


class LearningLedger:
    """Atomic append-only learning ledger backed by one local SQLite file."""

    def __init__(
        self,
        path: str | Path,
        *,
        clock: Callable[[], datetime] | None = None,
        must_exist: bool = False,
    ) -> None:
        if str(path) == ":memory:":
            raise ValueError("learning ledger must be file-backed; :memory: is forbidden")
        self.path = Path(path)
        if self.path.exists() and self.path.is_dir():
            raise ValueError("ledger path must be a file, not a directory")
        if type(must_exist) is not bool:
            raise TypeError("must_exist must be a boolean")
        self._must_exist = must_exist
        if not must_exist:
            self.path.parent.mkdir(parents=True, exist_ok=True)
        self._clock = clock or (lambda: datetime.now(timezone.utc))
        self._initialize()
        if not must_exist:
            self.verify_integrity()

    def _connect(
        self,
        *,
        read_only: bool = False,
        verification_path: Path | None = None,
    ) -> sqlite3.Connection:
        database_path = self.path if verification_path is None else verification_path
        database: str | Path = database_path
        if read_only:
            database = f"{database_path.absolute().as_uri()}?mode=ro"
        elif self._must_exist:
            database = f"{self.path.absolute().as_uri()}?mode=rw"
        connection = sqlite3.connect(
            database,
            timeout=30,
            isolation_level=None,
            uri=read_only or self._must_exist,
        )
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA foreign_keys = ON")
        connection.execute("PRAGMA busy_timeout = 30000")
        if read_only:
            connection.execute("PRAGMA query_only = ON")
        else:
            try:
                validate_sqlite_file_sizes(
                    self.path,
                    max_bytes=MAX_SHARED_STATE_FILE_BYTES,
                )
            except StorageError as error:
                connection.close()
                raise LedgerIntegrityError(str(error)) from error
        return connection

    def _initialize(self) -> None:
        if self._must_exist:
            self._verify_existing()
            return
        with closing(self._connect()) as connection:
            connection.execute("PRAGMA journal_mode = WAL")
            connection.executescript(
                """
                CREATE TABLE IF NOT EXISTS learning_ledger_meta (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                ) WITHOUT ROWID;

                CREATE TABLE IF NOT EXISTS learning_ledger_events (
                    sequence INTEGER PRIMARY KEY,
                    event_id TEXT NOT NULL UNIQUE,
                    event_type TEXT NOT NULL,
                    cycle_id TEXT NOT NULL,
                    semantic_key TEXT NOT NULL,
                    idempotency_key TEXT NOT NULL UNIQUE,
                    occurred_at TEXT NOT NULL,
                    recorded_at TEXT NOT NULL,
                    payload_json TEXT NOT NULL,
                    content_hash TEXT NOT NULL,
                    previous_hash TEXT NOT NULL,
                    event_hash TEXT NOT NULL UNIQUE,
                    schema_version INTEGER NOT NULL,
                    UNIQUE(event_type, semantic_key)
                );

                CREATE INDEX IF NOT EXISTS learning_ledger_cycle_sequence
                    ON learning_ledger_events(cycle_id, sequence);

                CREATE TRIGGER IF NOT EXISTS learning_ledger_no_update
                BEFORE UPDATE ON learning_ledger_events
                BEGIN
                    SELECT RAISE(ABORT, 'learning ledger events are immutable');
                END;

                CREATE TRIGGER IF NOT EXISTS learning_ledger_no_delete
                BEFORE DELETE ON learning_ledger_events
                BEGIN
                    SELECT RAISE(ABORT, 'learning ledger events are immutable');
                END;
                """
            )
            existing = connection.execute(
                "SELECT value FROM learning_ledger_meta WHERE key = 'schema_version'"
            ).fetchone()
            if existing is None:
                connection.execute(
                    "INSERT INTO learning_ledger_meta(key, value) VALUES ('schema_version', ?)",
                    (str(LEDGER_SCHEMA_VERSION),),
                )
            elif existing["value"] != str(LEDGER_SCHEMA_VERSION):
                raise LedgerIntegrityError("unsupported learning ledger schema version")

    def _verify_existing(self) -> None:
        try:
            with sqlite_verification_snapshot(
                self.path,
                label="learning ledger database",
                max_bytes=MAX_SHARED_STATE_FILE_BYTES,
            ) as snapshot:
                with closing(
                    self._connect(
                        read_only=True,
                        verification_path=snapshot.database,
                    )
                ) as connection:
                    query_only = connection.execute("PRAGMA query_only").fetchone()
                    if query_only is None or int(query_only[0]) != 1:
                        raise LedgerIntegrityError(
                            "learning ledger verification is not query-only"
                        )
                    mode = connection.execute("PRAGMA journal_mode").fetchone()
                    if mode is None or str(mode[0]).lower() != "wal":
                        raise LedgerIntegrityError(
                            "learning ledger database is not in WAL mode"
                        )
                    quick_check = connection.execute("PRAGMA quick_check").fetchall()
                    if not quick_check or any(
                        str(row[0]).lower() != "ok" for row in quick_check
                    ):
                        raise LedgerIntegrityError(
                            "learning ledger database integrity check failed"
                        )
                    self._verify_schema_locked(connection)
                    self._verify_integrity_locked(connection)
        except LedgerIntegrityError:
            raise
        except StorageError as error:
            raise LedgerIntegrityError(str(error)) from error
        except sqlite3.Error as error:
            raise LedgerIntegrityError(
                f"learning ledger verification failed: {type(error).__name__}"
            ) from error

    @staticmethod
    def _verify_schema_locked(connection: sqlite3.Connection) -> None:
        for table, expected_columns in _EXPECTED_LEDGER_COLUMNS.items():
            actual_columns = tuple(
                str(row["name"])
                for row in connection.execute(f'PRAGMA table_info("{table}")')
            )
            if actual_columns != expected_columns:
                raise LedgerIntegrityError(
                    f"learning ledger table {table} has an unexpected schema"
                )
        rows = connection.execute(
            """
            SELECT name, sql FROM sqlite_master
            WHERE type IN ('table', 'index', 'trigger', 'view')
              AND name NOT LIKE 'sqlite_%'
              AND sql IS NOT NULL
            """
        ).fetchall()
        actual_sql = {
            str(row["name"]): _normalized_schema_sql(row["sql"]) for row in rows
        }
        expected_sql = {
            name: _normalized_schema_sql(sql)
            for name, sql in _EXPECTED_LEDGER_SCHEMA_SQL.items()
        }
        expected_with_binding = {
            **expected_sql,
            STATE_BINDING_TABLE: _normalized_schema_sql(STATE_BINDING_TABLE_SQL),
        }
        if actual_sql not in (expected_sql, expected_with_binding):
            raise LedgerIntegrityError(
                "learning ledger tables, indexes, or immutability triggers do not match"
            )
        metadata = connection.execute(
            "SELECT key, value FROM learning_ledger_meta ORDER BY key"
        ).fetchall()
        if len(metadata) != 1 or (
            metadata[0]["key"] != "schema_version"
            or metadata[0]["value"] != str(LEDGER_SCHEMA_VERSION)
        ):
            raise LedgerIntegrityError("unsupported learning ledger schema metadata")

    def verify_integrity(self) -> str:
        """Verify every persisted event and return the current chain head."""

        with closing(self._connect()) as connection:
            return self._verify_integrity_locked(connection)

    def _verify_integrity_locked(self, connection: sqlite3.Connection) -> str:
        previous = LEDGER_GENESIS_HASH
        previous_recorded_at: datetime | None = None
        expected_sequence = 1
        rows = connection.execute(
            "SELECT * FROM learning_ledger_events ORDER BY sequence"
        ).fetchall()
        for row in rows:
            if row["sequence"] != expected_sequence:
                raise LedgerIntegrityError("learning ledger sequence is not contiguous")
            if row["schema_version"] != EVENT_SCHEMA_VERSION:
                raise LedgerIntegrityError("unsupported event schema version")
            if row["previous_hash"] != previous:
                raise LedgerIntegrityError("learning ledger previous hash mismatch")
            try:
                payload = json.loads(row["payload_json"])
            except (TypeError, json.JSONDecodeError) as error:
                raise LedgerIntegrityError("learning ledger payload is not valid JSON") from error
            if canonical_json(payload) != row["payload_json"]:
                raise LedgerIntegrityError("learning ledger payload is not canonical JSON")
            content = self._event_content(
                event_type=row["event_type"],
                cycle_id=row["cycle_id"],
                semantic_key=row["semantic_key"],
                idempotency_key=row["idempotency_key"],
                occurred_at=row["occurred_at"],
                payload=payload,
            )
            content_hash = domain_hash(EVENT_CONTENT_DOMAIN, content)
            if content_hash != row["content_hash"]:
                raise LedgerIntegrityError("learning ledger content hash mismatch")
            event_id = domain_hash(
                EVENT_ID_DOMAIN,
                {"content_hash": content_hash, "idempotency_key": row["idempotency_key"]},
            )
            if event_id != row["event_id"]:
                raise LedgerIntegrityError("learning ledger event id mismatch")
            event_hash = domain_hash(
                EVENT_CHAIN_DOMAIN,
                {
                    "sequence": row["sequence"],
                    "event_id": event_id,
                    "content_hash": content_hash,
                    "recorded_at": row["recorded_at"],
                    "previous_hash": previous,
                },
            )
            if event_hash != row["event_hash"]:
                raise LedgerIntegrityError("learning ledger event hash mismatch")
            _parse_iso(row["occurred_at"], "occurred_at")
            recorded_at = _parse_iso(row["recorded_at"], "recorded_at")
            if previous_recorded_at is not None and recorded_at < previous_recorded_at:
                raise LedgerIntegrityError("learning ledger recorded_at order regressed")
            previous = event_hash
            previous_recorded_at = recorded_at
            expected_sequence += 1
        return previous

    @staticmethod
    def _event_content(
        *,
        event_type: str,
        cycle_id: str,
        semantic_key: str,
        idempotency_key: str,
        occurred_at: str,
        payload: Mapping[str, Any],
    ) -> dict[str, Any]:
        return {
            "schema_version": EVENT_SCHEMA_VERSION,
            "event_type": event_type,
            "cycle_id": cycle_id,
            "semantic_key": semantic_key,
            "idempotency_key": idempotency_key,
            "occurred_at": occurred_at,
            "payload": payload,
        }

    def _append(
        self,
        *,
        event_type: str,
        cycle_id: str,
        semantic_key: str,
        idempotency_key: str,
        occurred_at: datetime,
        payload: Any,
        locked_validator: Callable[[sqlite3.Connection], None] | None = None,
    ) -> LedgerEvent:
        event_type = _text(event_type, "event_type")
        cycle_id = _text(cycle_id, "cycle_id")
        semantic_key = _text(semantic_key, "semantic_key")
        idempotency_key = _text(idempotency_key, "idempotency_key")
        occurred_at = _utc(occurred_at, "occurred_at")
        payload_data = canonical_data(payload)
        if not isinstance(payload_data, Mapping):
            raise TypeError("event payload must canonicalize to a mapping")
        payload_json = canonical_json(payload_data)
        if len(payload_json.encode("utf-8")) > MAX_LEARNING_EVENT_BYTES:
            raise LearningLedgerError("learning event payload exceeds its size limit")
        occurred_text = _iso(occurred_at)
        content = self._event_content(
            event_type=event_type,
            cycle_id=cycle_id,
            semantic_key=semantic_key,
            idempotency_key=idempotency_key,
            occurred_at=occurred_text,
            payload=payload_data,
        )
        content_hash = domain_hash(EVENT_CONTENT_DOMAIN, content)

        with closing(self._connect()) as connection:
            connection.execute("BEGIN IMMEDIATE")
            try:
                try:
                    enforce_sqlite_write_limit(
                        connection,
                        self.path,
                        max_bytes=MAX_SHARED_STATE_FILE_BYTES,
                        reserve_bytes=_LEARNING_WRITE_HEADROOM_BYTES,
                    )
                except StorageError as error:
                    raise LedgerIntegrityError(str(error)) from error
                previous = self._verify_integrity_locked(connection)
                existing = connection.execute(
                    "SELECT * FROM learning_ledger_events WHERE idempotency_key = ?",
                    (idempotency_key,),
                ).fetchone()
                if existing is not None:
                    if existing["content_hash"] != content_hash:
                        raise IdempotencyConflict(
                            f"idempotency key {idempotency_key!r} is bound to different content"
                        )
                    connection.commit()
                    return self._row_to_event(existing)

                if locked_validator is not None:
                    locked_validator(connection)

                duplicate = connection.execute(
                    "SELECT * FROM learning_ledger_events WHERE event_type = ? AND semantic_key = ?",
                    (event_type, semantic_key),
                ).fetchone()
                if duplicate is not None:
                    raise DuplicateConflict(
                        f"logical {event_type} record {semantic_key!r} already exists under another key"
                    )

                now = _utc(self._clock(), "ledger clock")
                head = connection.execute(
                    "SELECT sequence, recorded_at FROM learning_ledger_events ORDER BY sequence DESC LIMIT 1"
                ).fetchone()
                if head is not None and now < _parse_iso(head["recorded_at"], "recorded_at"):
                    raise LedgerBackdatingError("ledger clock moved behind the durable append head")
                if occurred_at > now:
                    raise LedgerBackdatingError("event occurred_at cannot be in the future")
                if (
                    event_type == "decision_cycle"
                    and now - occurred_at > MAX_DECISION_INGEST_LAG
                ):
                    raise LedgerBackdatingError(
                        "decision ingestion exceeded the prospective anti-backdating window"
                    )
                sequence = 1 if head is None else head["sequence"] + 1
                recorded_text = _iso(now)
                event_id = domain_hash(
                    EVENT_ID_DOMAIN,
                    {"content_hash": content_hash, "idempotency_key": idempotency_key},
                )
                event_hash = domain_hash(
                    EVENT_CHAIN_DOMAIN,
                    {
                        "sequence": sequence,
                        "event_id": event_id,
                        "content_hash": content_hash,
                        "recorded_at": recorded_text,
                        "previous_hash": previous,
                    },
                )
                connection.execute(
                    """
                    INSERT INTO learning_ledger_events(
                        sequence, event_id, event_type, cycle_id, semantic_key,
                        idempotency_key, occurred_at, recorded_at, payload_json,
                        content_hash, previous_hash, event_hash, schema_version
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        sequence,
                        event_id,
                        event_type,
                        cycle_id,
                        semantic_key,
                        idempotency_key,
                        occurred_text,
                        recorded_text,
                        payload_json,
                        content_hash,
                        previous,
                        event_hash,
                        EVENT_SCHEMA_VERSION,
                    ),
                )
                row = connection.execute(
                    "SELECT * FROM learning_ledger_events WHERE sequence = ?", (sequence,)
                ).fetchone()
                connection.commit()
                assert row is not None
                return self._row_to_event(row)
            except Exception:
                connection.rollback()
                raise

    def require_write_headroom(self) -> None:
        """Prove one bounded learning append can commit before entry dispatch."""

        with closing(self._connect()) as connection:
            connection.execute("BEGIN IMMEDIATE")
            try:
                enforce_sqlite_write_limit(
                    connection,
                    self.path,
                    max_bytes=MAX_SHARED_STATE_FILE_BYTES,
                    reserve_bytes=_LEARNING_WRITE_HEADROOM_BYTES,
                )
            except StorageError as error:
                raise LedgerIntegrityError(str(error)) from error
            finally:
                connection.rollback()

    @staticmethod
    def _row_to_event(row: sqlite3.Row) -> LedgerEvent:
        payload = json.loads(row["payload_json"])
        return LedgerEvent(
            sequence=row["sequence"],
            event_id=row["event_id"],
            event_type=row["event_type"],
            cycle_id=row["cycle_id"],
            semantic_key=row["semantic_key"],
            idempotency_key=row["idempotency_key"],
            occurred_at=_parse_iso(row["occurred_at"], "occurred_at"),
            recorded_at=_parse_iso(row["recorded_at"], "recorded_at"),
            payload=payload,
            content_hash=row["content_hash"],
            previous_hash=row["previous_hash"],
            event_hash=row["event_hash"],
            schema_version=row["schema_version"],
        )

    def events(self, *, cycle_id: str | None = None) -> tuple[LedgerEvent, ...]:
        """Read immutable events in chain order."""

        with closing(self._connect()) as connection:
            self._verify_integrity_locked(connection)
            if cycle_id is None:
                rows = connection.execute(
                    "SELECT * FROM learning_ledger_events ORDER BY sequence"
                ).fetchall()
            else:
                cycle_id = _text(cycle_id, "cycle_id")
                rows = connection.execute(
                    "SELECT * FROM learning_ledger_events WHERE cycle_id = ? ORDER BY sequence",
                    (cycle_id,),
                ).fetchall()
        return tuple(self._row_to_event(row) for row in rows)

    def _event_by_idempotency_key(self, idempotency_key: str) -> LedgerEvent | None:
        idempotency_key = _text(idempotency_key, "idempotency_key")
        with closing(self._connect()) as connection:
            self._verify_integrity_locked(connection)
            row = connection.execute(
                "SELECT * FROM learning_ledger_events WHERE idempotency_key = ?",
                (idempotency_key,),
            ).fetchone()
        return self._row_to_event(row) if row is not None else None

    def _cycle_events_locked(
        self, connection: sqlite3.Connection, cycle_id: str
    ) -> list[sqlite3.Row]:
        rows = connection.execute(
            "SELECT * FROM learning_ledger_events WHERE cycle_id = ? ORDER BY sequence",
            (cycle_id,),
        ).fetchall()
        if not rows or rows[0]["event_type"] != "decision_cycle":
            raise LifecycleError(f"decision cycle {cycle_id!r} does not exist")
        return rows

    def _cycle_events(self, cycle_id: str) -> tuple[LedgerEvent, ...]:
        events = self.events(cycle_id=cycle_id)
        if not events or events[0].event_type != "decision_cycle":
            raise LifecycleError(f"decision cycle {cycle_id!r} does not exist")
        return events

    @staticmethod
    def _decision_payload(events: Iterable[LedgerEvent]) -> Mapping[str, Any]:
        event = next((item for item in events if item.event_type == "decision_cycle"), None)
        if event is None:
            raise LifecycleError("decision event is missing")
        return event.payload

    @staticmethod
    def _require_after_decision(
        events: Iterable[LedgerEvent], timestamp: datetime, field_name: str
    ) -> None:
        decision = next(
            (item for item in events if item.event_type == "decision_cycle"), None
        )
        if decision is None:
            raise LifecycleError("decision event is missing")
        if timestamp < decision.occurred_at:
            raise LifecycleError(f"{field_name} must not precede the decision")

    @staticmethod
    def _locked_payloads(
        connection: sqlite3.Connection, cycle_id: str
    ) -> tuple[tuple[str, str, Mapping[str, Any]], ...]:
        rows = connection.execute(
            "SELECT event_type, event_hash, payload_json FROM learning_ledger_events "
            "WHERE cycle_id = ? ORDER BY sequence",
            (cycle_id,),
        ).fetchall()
        return tuple(
            (row["event_type"], row["event_hash"], json.loads(row["payload_json"]))
            for row in rows
        )

    def record_decision(self, cycle: DecisionCycle, *, idempotency_key: str) -> LedgerEvent:
        if not isinstance(cycle, DecisionCycle):
            raise TypeError("cycle must be DecisionCycle")
        return self._append(
            event_type="decision_cycle",
            cycle_id=cycle.cycle_id,
            semantic_key=cycle.cycle_id,
            idempotency_key=idempotency_key,
            occurred_at=cycle.decided_at,
            payload=cycle,
        )

    def record_approval(
        self, reference: ApprovalReference, *, idempotency_key: str
    ) -> LedgerEvent:
        if not isinstance(reference, ApprovalReference):
            raise TypeError("reference must be ApprovalReference")
        events = self._cycle_events(reference.cycle_id)
        decision = self._decision_payload(events)
        if decision["classification"] not in ("buy", "sell"):
            raise LifecycleError("abstention/unavailable cycles cannot have approvals")
        self._require_after_decision(events, reference.occurred_at, "approval occurred_at")
        prior = [
            item.payload
            for item in events
            if item.event_type == "approval_reference"
            and item.payload["reference_id"] == reference.reference_id
        ]
        if any(
            item["ticket_hash"] != reference.ticket_hash
            or item["authority_kind"] != reference.authority_kind
            for item in prior
        ):
            raise LifecycleError("approval reference identity changed across lifecycle states")

        def validate(connection: sqlite3.Connection) -> None:
            payloads = self._locked_payloads(connection, reference.cycle_id)
            same_reference = [
                payload
                for kind, _, payload in payloads
                if kind == "approval_reference"
                and payload["reference_id"] == reference.reference_id
            ]
            if any(
                item["ticket_hash"] != reference.ticket_hash
                or item["authority_kind"] != reference.authority_kind
                for item in same_reference
            ):
                raise LifecycleError(
                    "approval reference identity changed across lifecycle states"
                )

        return self._append(
            event_type="approval_reference",
            cycle_id=reference.cycle_id,
            semantic_key=f"{reference.reference_id}:{reference.state.value}",
            idempotency_key=idempotency_key,
            occurred_at=reference.occurred_at,
            payload=reference,
            locked_validator=validate,
        )

    def record_execution(
        self, reference: ExecutionReference, *, idempotency_key: str
    ) -> LedgerEvent:
        if not isinstance(reference, ExecutionReference):
            raise TypeError("reference must be ExecutionReference")
        events = self._cycle_events(reference.cycle_id)
        decision = self._decision_payload(events)
        if decision["classification"] not in ("buy", "sell"):
            raise LifecycleError("abstention/unavailable cycles cannot have execution")
        self._require_after_decision(events, reference.occurred_at, "execution occurred_at")
        prior = [
            item.payload
            for item in events
            if item.event_type == "execution_reference"
            and item.payload["command_id"] == reference.command_id
        ]
        if any(
            tuple(item["client_order_ids"]) != reference.client_order_ids
            for item in prior
        ):
            raise LifecycleError("execution client-order identity changed across states")

        def validate(connection: sqlite3.Connection) -> None:
            payloads = self._locked_payloads(connection, reference.cycle_id)
            same_command = [
                payload
                for kind, _, payload in payloads
                if kind == "execution_reference"
                and payload["command_id"] == reference.command_id
            ]
            if any(
                tuple(item["client_order_ids"]) != reference.client_order_ids
                for item in same_command
            ):
                raise LifecycleError(
                    "execution client-order identity changed across lifecycle states"
                )

        return self._append(
            event_type="execution_reference",
            cycle_id=reference.cycle_id,
            semantic_key=f"{reference.command_id}:{reference.state.value}",
            idempotency_key=idempotency_key,
            occurred_at=reference.occurred_at,
            payload=reference,
            locked_validator=validate,
        )

    def record_recovery_execution(
        self,
        reference: RecoveryExecutionReference,
        *,
        idempotency_key: str,
    ) -> LedgerEvent:
        if not isinstance(reference, RecoveryExecutionReference):
            raise TypeError("reference must be RecoveryExecutionReference")
        events = self._cycle_events(reference.cycle_id)
        self._require_after_decision(
            events, reference.occurred_at, "recovery execution occurred_at"
        )
        if not any(
            item.event_type == "execution_reference"
            and item.payload["command_id"] == reference.parent_command_id
            for item in events
        ):
            raise LifecycleError(
                "recovery execution has no parent execution lifecycle reference"
            )
        prior = [
            item.payload
            for item in events
            if item.event_type == "recovery_execution_reference"
            and item.payload["recovery_command_id"]
            == reference.recovery_command_id
        ]
        if any(
            item["parent_command_id"] != reference.parent_command_id
            or item["kind"] != reference.kind
            or item["recovery_record_hash"] != reference.recovery_record_hash
            or tuple(item["client_order_ids"]) != reference.client_order_ids
            for item in prior
        ):
            raise LifecycleError(
                "recovery execution identity changed across observations"
            )

        def validate(connection: sqlite3.Connection) -> None:
            payloads = self._locked_payloads(connection, reference.cycle_id)
            if not any(
                kind == "execution_reference"
                and payload["command_id"] == reference.parent_command_id
                for kind, _, payload in payloads
            ):
                raise LifecycleError(
                    "recovery execution lost its parent lifecycle reference"
                )
            same = [
                payload
                for kind, _, payload in payloads
                if kind == "recovery_execution_reference"
                and payload["recovery_command_id"]
                == reference.recovery_command_id
            ]
            if any(
                payload["parent_command_id"] != reference.parent_command_id
                or payload["kind"] != reference.kind
                or payload["recovery_record_hash"]
                != reference.recovery_record_hash
                or tuple(payload["client_order_ids"])
                != reference.client_order_ids
                for payload in same
            ):
                raise LifecycleError(
                    "recovery execution identity changed concurrently"
                )

        return self._append(
            event_type="recovery_execution_reference",
            cycle_id=reference.cycle_id,
            semantic_key=reference.recovery_command_id,
            idempotency_key=idempotency_key,
            occurred_at=reference.occurred_at,
            payload=reference,
            locked_validator=validate,
        )

    def record_fill(self, fill: VenueFill, *, idempotency_key: str) -> LedgerEvent:
        if not isinstance(fill, VenueFill):
            raise TypeError("fill must be VenueFill")
        events = self._cycle_events(fill.cycle_id)
        self._require_after_decision(events, fill.venue_occurred_at, "fill occurred_at")
        matching_commands = {
            item.payload["command_id"]
            for item in events
            if item.event_type == "execution_reference"
        }
        if fill.command_id not in matching_commands:
            raise LifecycleError("fill command_id has no execution lifecycle reference")
        decision = self._decision_payload(events)
        matching_client_ids = {
            client_id
            for item in events
            if item.event_type == "execution_reference"
            and item.payload["command_id"] == fill.command_id
            for client_id in item.payload["client_order_ids"]
        }
        matching_client_ids.update(
            client_id
            for item in events
            if item.event_type == "recovery_execution_reference"
            and item.payload["parent_command_id"] == fill.command_id
            for client_id in item.payload["client_order_ids"]
        )
        if fill.client_order_id not in matching_client_ids:
            raise LifecycleError("fill client_order_id is not bound to its command")
        decision_side = DecisionClass(decision["classification"])
        expected_side = (
            decision_side
            if fill.role is FillRole.ENTRY
            else (
                DecisionClass.SELL
                if decision_side is DecisionClass.BUY
                else DecisionClass.BUY
            )
        )
        if fill.side is not expected_side:
            raise LifecycleError("fill side is inconsistent with its entry/exit role")
        settlement_asset = decision["bracket"]["settlement_asset"]
        if fill.fee_asset != settlement_asset:
            raise LifecycleError("fill fee asset must match decision settlement asset")

        def validate(connection: sqlite3.Connection) -> None:
            payloads = self._locked_payloads(connection, fill.cycle_id)
            closes = [
                payload for kind, _, payload in payloads if kind == "close_outcome"
            ]
            if closes:
                completed_at = _parse_iso(
                    closes[-1]["observation"]["completed_at"], "completed_at"
                )
                if fill.venue_occurred_at > completed_at:
                    raise LifecycleError(
                        "post-close supplemental fill must have occurred by the close"
                    )
            commands = {
                payload["command_id"]
                for kind, _, payload in payloads
                if kind == "execution_reference"
            }
            if fill.command_id not in commands:
                raise LifecycleError("fill command_id has no execution lifecycle reference")
            client_ids = {
                client_id
                for kind, _, payload in payloads
                if kind == "execution_reference"
                and payload["command_id"] == fill.command_id
                for client_id in payload["client_order_ids"]
            }
            client_ids.update(
                client_id
                for kind, _, payload in payloads
                if kind == "recovery_execution_reference"
                and payload["parent_command_id"] == fill.command_id
                for client_id in payload["client_order_ids"]
            )
            if fill.client_order_id not in client_ids:
                raise LifecycleError("fill client_order_id is not bound to its command")
            persisted_fills = [
                payload for kind, _, payload in payloads if kind == "venue_fill"
            ]
            entry_quantity = _sum_exact(
                (
                    Decimal(payload["quantity"])
                    for payload in persisted_fills
                    if payload["role"] == "entry"
                ),
            )
            exit_quantity = _sum_exact(
                (
                    Decimal(payload["quantity"])
                    for payload in persisted_fills
                    if payload["role"] in ("exit", "protection")
                ),
            )
            if fill.role is FillRole.ENTRY:
                entry_quantity = _add_exact(entry_quantity, fill.quantity)
            else:
                exit_quantity = _add_exact(exit_quantity, fill.quantity)
            planned_quantity = Decimal(decision["bracket"]["quantity"])
            if not closes and entry_quantity > planned_quantity:
                raise LifecycleError("entry fills exceed the proposed bracket quantity")
            if not closes and exit_quantity > entry_quantity:
                raise LifecycleError("exit fills exceed recorded entry fills")

        return self._append(
            event_type="venue_fill",
            cycle_id=fill.cycle_id,
            semantic_key=domain_hash(
                FILL_NATURAL_KEY_DOMAIN,
                {
                    "venue": decision["venue"],
                    "environment": decision["environment"],
                    "order_id": fill.order_id,
                    "fill_id": fill.fill_id,
                },
            ),
            idempotency_key=idempotency_key,
            occurred_at=fill.venue_occurred_at,
            payload=fill,
            locked_validator=validate,
        )

    def record_funding(
        self, payment: FundingPayment, *, idempotency_key: str
    ) -> LedgerEvent:
        if not isinstance(payment, FundingPayment):
            raise TypeError("payment must be FundingPayment")
        events = self._cycle_events(payment.cycle_id)
        self._require_after_decision(events, payment.occurred_at, "funding occurred_at")
        if not any(item.event_type == "execution_reference" for item in events):
            raise LifecycleError("funding requires an execution lifecycle reference")
        decision = self._decision_payload(events)
        if payment.asset != decision["bracket"]["settlement_asset"]:
            raise LifecycleError("funding asset must match decision settlement asset")

        def validate(connection: sqlite3.Connection) -> None:
            payloads = self._locked_payloads(connection, payment.cycle_id)
            closes = [
                payload for kind, _, payload in payloads if kind == "close_outcome"
            ]
            if closes:
                completed_at = _parse_iso(
                    closes[-1]["observation"]["completed_at"], "completed_at"
                )
                if payment.occurred_at > completed_at:
                    raise LifecycleError(
                        "post-close supplemental funding must have occurred by the close"
                    )
            if not any(kind == "execution_reference" for kind, _, _ in payloads):
                raise LifecycleError("funding requires an execution lifecycle reference")

        return self._append(
            event_type="funding_payment",
            cycle_id=payment.cycle_id,
            semantic_key=payment.funding_id,
            idempotency_key=idempotency_key,
            occurred_at=payment.occurred_at,
            payload=payment,
            locked_validator=validate,
        )

    def record_market_path(
        self, path: MarketPathEvidence, *, idempotency_key: str
    ) -> LedgerEvent:
        """Commit source bars and derive actual MAE/MFE when entry fills exist."""

        if not isinstance(path, MarketPathEvidence):
            raise TypeError("path must be MarketPathEvidence")
        replay = self._event_by_idempotency_key(idempotency_key)
        if replay is not None:
            if (
                replay.event_type == "market_path"
                and replay.payload["market_path"] == canonical_data(path)
            ):
                return replay
            raise IdempotencyConflict(
                f"idempotency key {idempotency_key!r} is bound to different content"
            )
        events = self._cycle_events(path.cycle_id)
        self._require_after_decision(events, path.captured_at, "path captured_at")
        decision_time = events[0].occurred_at
        if path.window_started_at < decision_time:
            raise LifecycleError("outcome/counterfactual path bars must not precede the decision")
        decision = self._decision_payload(events)
        path_data = canonical_data(path)
        payload: dict[str, Any] = {
            "market_path": path_data,
            "path_hash": domain_hash(MARKET_PATH_DOMAIN, path_data),
            "excursion_derivation_version": "filled-entry-extrema-r/v1",
            "actual_excursion": None,
            "entry_fill_event_hashes": tuple(
                item.event_hash
                for item in events
                if item.event_type == "venue_fill" and item.payload["role"] == "entry"
            ),
        }
        entry_fills = [
            item.payload
            for item in events
            if item.event_type == "venue_fill" and item.payload["role"] == "entry"
        ]
        if entry_fills:
            earliest_entry_at = min(
                _parse_iso(item["venue_occurred_at"], "venue_occurred_at")
                for item in entry_fills
            )
            if path.window_started_at != earliest_entry_at:
                raise LifecycleError(
                    "executed-trade market path must start exactly at the first entry fill"
                )
            total_quantity = _sum_exact(
                Decimal(item["quantity"]) for item in entry_fills
            )
            weighted = _sum_exact(
                _multiply_exact(Decimal(item["price"]), Decimal(item["quantity"]))
                for item in entry_fills
            )
            entry = _ratio(weighted, total_quantity)
            stop = Decimal(decision["bracket"]["stop_price"])
            risk_unit = abs(_subtract_exact(entry, stop))
            if risk_unit == 0:
                raise LifecycleError("filled entry equals stop; excursion R is undefined")
            highs = [bar.high for bar in path.bars]
            lows = [bar.low for bar in path.bars]
            if decision["classification"] == "buy":
                adverse = max(Decimal(0), _subtract_exact(entry, min(lows)))
                favorable = max(Decimal(0), _subtract_exact(max(highs), entry))
            else:
                adverse = max(Decimal(0), _subtract_exact(max(highs), entry))
                favorable = max(Decimal(0), _subtract_exact(entry, min(lows)))
            payload["actual_excursion"] = {
                "entry_price": entry,
                "risk_per_unit": risk_unit,
                "mae_r": _ratio(adverse, risk_unit),
                "mfe_r": _ratio(favorable, risk_unit),
            }

        entry_basis = tuple(payload["entry_fill_event_hashes"])

        def validate(connection: sqlite3.Connection) -> None:
            payloads = self._locked_payloads(connection, path.cycle_id)
            closes = [
                payload for kind, _, payload in payloads if kind == "close_outcome"
            ]
            if closes:
                completed_at = _parse_iso(
                    closes[-1]["observation"]["completed_at"], "completed_at"
                )
                if path.window_ended_at != completed_at:
                    raise LifecycleError(
                        "post-close market path must cover the exact entry-to-close window"
                    )
            current_basis = tuple(
                event_hash
                for kind, event_hash, item_payload in payloads
                if kind == "venue_fill" and item_payload["role"] == "entry"
            )
            if current_basis != entry_basis:
                raise LifecycleError("entry-fill evidence changed while deriving market path")

        return self._append(
            event_type="market_path",
            cycle_id=path.cycle_id,
            semantic_key=path.path_id,
            idempotency_key=idempotency_key,
            occurred_at=path.captured_at,
            payload=payload,
            locked_validator=validate,
        )

    def record_close(
        self, close: CloseObservation, *, idempotency_key: str
    ) -> LedgerEvent:
        """Record a close and derive fees, funding, net P&L, and realized R."""

        if not isinstance(close, CloseObservation):
            raise TypeError("close must be CloseObservation")
        replay = self._event_by_idempotency_key(idempotency_key)
        if replay is not None:
            if (
                replay.event_type == "close_outcome"
                and replay.payload["observation"] == canonical_data(close)
            ):
                return replay
            raise IdempotencyConflict(
                f"idempotency key {idempotency_key!r} is bound to different content"
            )
        events = self._cycle_events(close.cycle_id)
        self._require_after_decision(events, close.completed_at, "close completed_at")
        decision = self._decision_payload(events)
        if decision["classification"] not in ("buy", "sell"):
            raise LifecycleError("only a position decision can close")
        if not any(
            item.event_type == "venue_fill" and item.payload["role"] == "entry"
            for item in events
        ):
            raise LifecycleError("close requires at least one entry fill")
        fill_command_ids = {
            item.payload["command_id"]
            for item in events
            if item.event_type == "venue_fill"
        }
        reconciled_command_ids = {
            item.payload["command_id"]
            for item in events
            if item.event_type == "execution_reference"
            and item.payload["state"] == "reconciled"
        }
        if not fill_command_ids.issubset(reconciled_command_ids):
            raise LifecycleError(
                "close requires reconciliation of every command owning a fill"
            )
        entry_fill_hashes = tuple(
            item.event_hash
            for item in events
            if item.event_type == "venue_fill" and item.payload["role"] == "entry"
        )
        eligible_paths = tuple(
            item
            for item in events
            if (
            item.event_type == "market_path"
            and item.payload["actual_excursion"] is not None
            and tuple(item.payload["entry_fill_event_hashes"]) == entry_fill_hashes
            and item.payload["market_path"]["window_ended_at"]
            == _iso(close.completed_at)
            )
        )
        if not eligible_paths:
            raise LifecycleError(
                "close requires MAE/MFE over the exact entry-to-close window and complete fills"
            )
        selected_excursion_path = eligible_paths[-1]
        settlement_asset = decision["bracket"]["settlement_asset"]
        if close.pnl_asset != settlement_asset:
            raise LifecycleError("close P&L asset must match decision settlement asset")
        factual_times = tuple(
            item.occurred_at
            for item in events
            if item.event_type in ("venue_fill", "funding_payment")
        )
        if factual_times and close.completed_at < max(factual_times):
            raise LifecycleError("close completed_at precedes recorded trade evidence")
        fees = _sum_exact(
            Decimal(item.payload["fee"])
            for item in events
            if item.event_type == "venue_fill"
        )
        funding = _sum_exact(
            Decimal(item.payload["amount"])
            for item in events
            if item.event_type == "funding_payment"
        )
        net_pnl = _add_exact(_subtract_exact(close.gross_pnl, fees), funding)
        entry_quantity = _sum_exact(
            (
                Decimal(item.payload["quantity"])
                for item in events
                if item.event_type == "venue_fill" and item.payload["role"] == "entry"
            ),
        )
        exit_quantity = _sum_exact(
            (
                Decimal(item.payload["quantity"])
                for item in events
                if item.event_type == "venue_fill"
                and item.payload["role"] in ("exit", "protection")
            ),
        )
        if exit_quantity != entry_quantity:
            raise LifecycleError("close requires reconciled flat fill quantities")
        planned_risk_amount = Decimal(decision["bracket"]["risk_amount"])
        planned_quantity = Decimal(decision["bracket"]["quantity"])
        risk_amount = _multiply_exact(
            planned_risk_amount, _ratio(entry_quantity, planned_quantity)
        )
        payload = {
            "observation": close,
            "total_fees": fees,
            "total_funding": funding,
            "net_pnl": net_pnl,
            "realized_r": _ratio(net_pnl, risk_amount),
            "realized_r_risk_basis_amount": risk_amount,
            "pnl_derivation_version": "gross-minus-fees-plus-funding/v1",
            "realized_r_derivation_version": "net-pnl-over-filled-share-of-planned-risk/v1",
            "excursion_path_event_hash": selected_excursion_path.event_hash,
            "excursion_path_hash": selected_excursion_path.payload["path_hash"],
            "gross_pnl_fill_basis_hashes": tuple(
                item.event_hash for item in events if item.event_type == "venue_fill"
            ),
            "basis_event_hashes": tuple(
                item.event_hash
                for item in events
                if item.event_type in ("venue_fill", "funding_payment", "market_path")
            ),
        }

        basis = tuple(payload["basis_event_hashes"])

        def validate(connection: sqlite3.Connection) -> None:
            payloads = self._locked_payloads(connection, close.cycle_id)
            current_basis = tuple(
                event_hash
                for kind, event_hash, _ in payloads
                if kind in ("venue_fill", "funding_payment", "market_path")
            )
            if current_basis != basis:
                raise LifecycleError("trade evidence changed while deriving close outcome")
            if any(kind == "close_outcome" for kind, _, _ in payloads):
                raise DuplicateConflict("cycle already has a close outcome")

        return self._append(
            event_type="close_outcome",
            cycle_id=close.cycle_id,
            semantic_key=close.cycle_id,
            idempotency_key=idempotency_key,
            occurred_at=close.completed_at,
            payload=payload,
            locked_validator=validate,
        )

    def record_close_pnl_correction(
        self,
        correction: ClosePnlCorrection,
        *,
        idempotency_key: str,
    ) -> LedgerEvent:
        """Append a versioned gross-P&L correction bound to current fill evidence."""

        if not isinstance(correction, ClosePnlCorrection):
            raise TypeError("correction must be ClosePnlCorrection")
        replay = self._event_by_idempotency_key(idempotency_key)
        if replay is not None:
            if (
                replay.event_type == "close_pnl_correction"
                and replay.payload["observation"] == canonical_data(correction)
            ):
                return replay
            raise IdempotencyConflict(
                f"idempotency key {idempotency_key!r} is bound to different content"
            )
        events = self._cycle_events(correction.cycle_id)
        close_event = next(
            (item for item in events if item.event_type == "close_outcome"), None
        )
        if close_event is None:
            raise LifecycleError("close P&L correction requires a close outcome")
        completed_at = _parse_iso(
            close_event.payload["observation"]["completed_at"], "completed_at"
        )
        if correction.observed_at < completed_at:
            raise LifecycleError("close P&L correction cannot predate the close")
        decision = self._decision_payload(events)
        if correction.pnl_asset != decision["bracket"]["settlement_asset"]:
            raise LifecycleError("correction P&L asset must match decision settlement asset")
        fills = tuple(item for item in events if item.event_type == "venue_fill")
        fill_command_ids = {item.payload["command_id"] for item in fills}
        reconciled_command_ids = {
            item.payload["command_id"]
            for item in events
            if item.event_type == "execution_reference"
            and item.payload["state"] == "reconciled"
        }
        if not fill_command_ids.issubset(reconciled_command_ids):
            raise LifecycleError(
                "correction requires reconciliation of every command owning a fill"
            )
        entry_quantity = _sum_exact(
            Decimal(item.payload["quantity"])
            for item in fills
            if item.payload["role"] == "entry"
        )
        exit_quantity = _sum_exact(
            Decimal(item.payload["quantity"])
            for item in fills
            if item.payload["role"] in ("exit", "protection")
        )
        if not entry_quantity or entry_quantity != exit_quantity:
            raise LifecycleError("correction requires reconciled flat fill quantities")
        fees = _sum_exact(Decimal(item.payload["fee"]) for item in fills)
        funding_events = tuple(
            item for item in events if item.event_type == "funding_payment"
        )
        funding = _sum_exact(
            Decimal(item.payload["amount"]) for item in funding_events
        )
        net_pnl = _add_exact(_subtract_exact(correction.gross_pnl, fees), funding)
        risk_basis = _multiply_exact(
            Decimal(decision["bracket"]["risk_amount"]),
            _ratio(entry_quantity, Decimal(decision["bracket"]["quantity"])),
        )
        prior_corrections = tuple(
            item for item in events if item.event_type == "close_pnl_correction"
        )
        supersedes = prior_corrections[-1] if prior_corrections else close_event
        fill_basis = tuple(item.event_hash for item in fills)
        net_basis = tuple(
            item.event_hash
            for item in events
            if item.event_type in ("venue_fill", "funding_payment")
        )
        payload = {
            "observation": correction,
            "close_event_hash": close_event.event_hash,
            "supersedes_event_hash": supersedes.event_hash,
            "gross_pnl_fill_basis_hashes": fill_basis,
            "net_pnl_basis_event_hashes": net_basis,
            "total_fees": fees,
            "total_funding": funding,
            "net_pnl": net_pnl,
            "realized_r_risk_basis_amount": risk_basis,
            "realized_r": _ratio(net_pnl, risk_basis),
            "derivation_version": "corrected-gross-current-costs-filled-risk/v1",
        }

        def validate(connection: sqlite3.Connection) -> None:
            payloads = self._locked_payloads(connection, correction.cycle_id)
            current_fill_basis = tuple(
                event_hash
                for kind, event_hash, _ in payloads
                if kind == "venue_fill"
            )
            current_net_basis = tuple(
                event_hash
                for kind, event_hash, _ in payloads
                if kind in ("venue_fill", "funding_payment")
            )
            current_superseded = tuple(
                event_hash
                for kind, event_hash, _ in payloads
                if kind in ("close_outcome", "close_pnl_correction")
            )[-1]
            if current_fill_basis != fill_basis or current_net_basis != net_basis:
                raise LifecycleError(
                    "trade evidence changed while deriving close P&L correction"
                )
            if current_superseded != supersedes.event_hash:
                raise LifecycleError("close P&L correction supersession changed")

        return self._append(
            event_type="close_pnl_correction",
            cycle_id=correction.cycle_id,
            semantic_key=domain_hash(
                CLOSE_CORRECTION_KEY_DOMAIN,
                {
                    "cycle_id": correction.cycle_id,
                    "correction_id": correction.correction_id,
                },
            ),
            idempotency_key=idempotency_key,
            occurred_at=correction.observed_at,
            payload=payload,
            locked_validator=validate,
        )

    def record_counterfactual(
        self,
        cycle_id: str,
        path_id: str,
        spec: CounterfactualSpec,
        *,
        idempotency_key: str,
    ) -> LedgerEvent:
        """Derive a conservative bracket counterfactual from committed bars.

        The caller supplies parameters, never an outcome.  If stop and target
        are touched in the same bar, the stop is selected because intrabar
        ordering is unknowable from OHLC evidence.
        """

        cycle_id = _text(cycle_id, "cycle_id")
        path_id = _text(path_id, "path_id")
        if not isinstance(spec, CounterfactualSpec):
            raise TypeError("spec must be CounterfactualSpec")
        events = self._cycle_events(cycle_id)
        path_event = next(
            (
                item
                for item in events
                if item.event_type == "market_path"
                and item.payload["market_path"]["path_id"] == path_id
            ),
            None,
        )
        if path_event is None:
            raise LifecycleError("counterfactual requires an immutable market path")
        raw_bars = path_event.payload["market_path"]["bars"][: spec.max_bars]
        if not raw_bars:
            raise LifecycleError("counterfactual market path is empty")
        risk = abs(_subtract_exact(spec.entry_price, spec.stop_price))
        target_r = _ratio(
            abs(_subtract_exact(spec.target_price, spec.entry_price)), risk
        )
        outcome = "not_entered"
        gross_r: Decimal | None = None
        entry_bar_opened_at: str | None = None
        entry_bar_closed_at: str | None = None
        entry_time_precision: str | None = None
        exit_bar_opened_at: str | None = None
        exit_bar_closed_at: str | None = None
        exit_time_precision: str | None = None
        entered = False
        same_bar_conservative_stop = False
        same_bar_entry_ambiguity = False
        same_bar_target_ignored = False
        bars_evaluated = 0
        for index, bar in enumerate(raw_bars):
            bars_evaluated = index + 1
            high = Decimal(bar["high"])
            low = Decimal(bar["low"])
            opened = Decimal(bar["open"])
            closed = Decimal(bar["close"])
            entered_at_open = False
            entered_this_bar = False
            if not entered:
                if spec.entry_rule is CounterfactualEntryRule.WINDOW_OPEN:
                    if index != 0:
                        raise AssertionError("window-open entry must be evaluated on first bar")
                    if opened != spec.entry_price:
                        raise LifecycleError(
                            "window_open counterfactual entry must equal the first bar open"
                        )
                    entered = True
                    entered_this_bar = True
                    entered_at_open = True
                    entry_bar_opened_at = bar["opened_at"]
                    entry_bar_closed_at = bar["closed_at"]
                    entry_time_precision = "exact_window_open"
                else:
                    if not low <= spec.entry_price <= high:
                        continue
                    entered = True
                    entered_this_bar = True
                    entry_bar_opened_at = bar["opened_at"]
                    entry_bar_closed_at = bar["closed_at"]
                    entered_at_open = opened == spec.entry_price
                    entry_time_precision = (
                        "exact_bar_open" if entered_at_open else "bar_interval"
                    )
                    same_bar_entry_ambiguity = not entered_at_open
            if spec.side is DecisionClass.BUY:
                stop_hit = low <= spec.stop_price
                target_hit = high >= spec.target_price
                close_proves_post_entry_target = closed >= spec.target_price
            else:
                stop_hit = high >= spec.stop_price
                target_hit = low <= spec.target_price
                close_proves_post_entry_target = closed <= spec.target_price
            if stop_hit:
                outcome = "stop"
                gross_r = Decimal(-1)
                exit_bar_opened_at = bar["opened_at"]
                exit_bar_closed_at = bar["closed_at"]
                exit_time_precision = "bar_interval"
                same_bar_conservative_stop = target_hit
                break
            if target_hit:
                if (
                    entered_this_bar
                    and not entered_at_open
                    and not close_proves_post_entry_target
                ):
                    same_bar_target_ignored = True
                    continue
                outcome = "target"
                gross_r = target_r
                exit_bar_opened_at = bar["opened_at"]
                exit_bar_closed_at = bar["closed_at"]
                exit_time_precision = "bar_interval"
                break
        if not entered:
            gross_r = Decimal(0)
            assumed_cost_r = Decimal(0)
        elif gross_r is None:
            outcome = "time_mark"
            final_close = Decimal(raw_bars[-1]["close"])
            move = _subtract_exact(final_close, spec.entry_price)
            if spec.side is DecisionClass.SELL:
                move = -move
            gross_r = _ratio(move, risk)
            exit_bar_opened_at = raw_bars[-1]["opened_at"]
            exit_bar_closed_at = raw_bars[-1]["closed_at"]
            exit_time_precision = "exact_bar_close"
            assumed_cost_r = spec.cost_r
        else:
            assumed_cost_r = spec.cost_r
        payload = {
            "spec": spec,
            "path_id": path_id,
            "path_hash": path_event.payload["path_hash"],
            "market_source_snapshot_hash": path_event.payload["market_path"][
                "source_snapshot_hash"
            ],
            "derivation_version": COUNTERFACTUAL_DERIVATION_VERSION,
            "outcome": outcome,
            "entered": entered,
            "entry_bar_opened_at": entry_bar_opened_at,
            "entry_bar_closed_at": entry_bar_closed_at,
            "entry_time_precision": entry_time_precision,
            "gross_r": gross_r,
            "assumed_cost_r_applied": assumed_cost_r,
            "net_r_after_assumed_cost": _subtract_exact(gross_r, assumed_cost_r),
            "exit_bar_opened_at": exit_bar_opened_at,
            "exit_bar_closed_at": exit_bar_closed_at,
            "exit_time_precision": exit_time_precision,
            "bars_evaluated": bars_evaluated,
            "same_bar_conservative_stop": same_bar_conservative_stop,
            "same_bar_entry_ambiguity": same_bar_entry_ambiguity,
            "same_bar_target_ignored": same_bar_target_ignored,
            "interpretation": "counterfactual_description_not_causal_evidence",
        }
        return self._append(
            event_type="counterfactual",
            cycle_id=cycle_id,
            semantic_key=domain_hash(
                COUNTERFACTUAL_KEY_DOMAIN,
                {
                    "cycle_id": cycle_id,
                    "scenario_id": spec.scenario_id,
                    "scenario_version": spec.scenario_version,
                    "entry_rule": spec.entry_rule,
                },
            ),
            idempotency_key=idempotency_key,
            occurred_at=path_event.occurred_at,
            payload=payload,
        )
